GET https://api.codingthailand.com/api/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmNvZGluZ3RoYWlsYW5kLmNvbVwvYXBpXC9sb2dpbiIsImlhdCI6MTY3ODU0NDI5NywiZXhwIjoxNjc4OTc2Mjk3LCJuYmYiOjE2Nzg1NDQyOTcsImp0aSI6InhkRFo5MGVpM0RWQ0xLd08iLCJzdWIiOjM5ODMsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEiLCJ1c2VyIjp7ImlkIjozOTgzLCJyb2xlIjoibWVtYmVyIn19.UmT7KaMD2DmLqXO8Sop6zVhbY50EtAwiWxc6wZeIs1E

###

POST https://api.codingthailand.com/api/editprofile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmNvZGluZ3RoYWlsYW5kLmNvbVwvYXBpXC9sb2dpbiIsImlhdCI6MTY3ODU0NDI5NywiZXhwIjoxNjc4OTc2Mjk3LCJuYmYiOjE2Nzg1NDQyOTcsImp0aSI6InhkRFo5MGVpM0RWQ0xLd08iLCJzdWIiOjM5ODMsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEiLCJ1c2VyIjp7ImlkIjozOTgzLCJyb2xlIjoibWVtYmVyIn19.UmT7KaMD2DmLqXO8Sop6zVhbY50EtAwiWxc6wZeIs1E

{
  "name": "🐵"
}

###

GET https://api.codingthailand.com/api/course
###
